eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8866/eureka/
      
            
datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.164.206:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC